[package]
name = "export-personal-works"
version = "0.1.0"
authors = ["Hiroshi Sugawara <5000164@users.noreply.github.com>"]
edition = "2018"

[dependencies]
ureq = "2.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
